<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260305013036_CreateUrlTable extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE url 
            (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            original_url TEXT NOT NULL, 
            short_code VARCHAR(50) NOT NULL, 
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            click_count INT DEFAULT 0 NOT NULL, 
            expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
            PRIMARY KEY (id))
        ');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F47645AE17D2FE0D ON url (short_code)');
        $this->addSql('CREATE INDEX idx_short_code ON url (short_code)');
        $this->addSql('CREATE INDEX idx_created_at ON url (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX idx_created_at');
        $this->addSql('DROP INDEX idx_short_code');
        $this->addSql('DROP INDEX UNIQ_F47645AE17D2FE0D');
        $this->addSql('DROP TABLE url');
    }
}
