<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260325184120_CreateClickEventTable extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE click_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, referer VARCHAR(500) DEFAULT NULL, clicked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, url_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4E2B6A0B81CFDAE7 ON click_event (url_id)');
        $this->addSql('CREATE INDEX idx_clicked_at ON click_event (clicked_at)');
        $this->addSql('ALTER TABLE click_event ADD CONSTRAINT FK_4E2B6A0B81CFDAE7 FOREIGN KEY (url_id) REFERENCES url (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE click_event DROP CONSTRAINT FK_4E2B6A0B81CFDAE7');
        $this->addSql('DROP TABLE click_event');
    }
}
