<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260325184558_CreateBlacklistedDomainTable extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE blacklisted_domain (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, domain VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C05BCF9A7A91E0B ON blacklisted_domain (domain)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE blacklisted_domain');
    }
}
